# Generated by Django 4.1.3 on 2022-11-23 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agenda',
            name='cantidad_dias',
        ),
        migrations.RemoveField(
            model_name='agenda',
            name='programa_f',
        ),
        migrations.AddField(
            model_name='agenda',
            name='dias',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Jornada'),
        ),
        migrations.AddField(
            model_name='agenda',
            name='hora_Fin',
            field=models.TimeField(blank=True, null=True, verbose_name='Hora fin'),
        ),
        migrations.AddField(
            model_name='agenda',
            name='hora_Inicio',
            field=models.TimeField(blank=True, null=True, verbose_name='Hora de Inicio'),
        ),
    ]
