# Generated by Django 4.1.3 on 2022-11-23 03:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
        ('agenda', '0002_remove_agenda_cantidad_dias_remove_agenda_programa_f_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='dias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dias_Semana', models.CharField(blank=True, max_length=200, null=True, verbose_name='Dias')),
            ],
            options={
                'verbose_name': 'Dia ',
                'verbose_name_plural': 'Dias',
            },
        ),
        migrations.RemoveField(
            model_name='agenda',
            name='dias',
        ),
        migrations.RemoveField(
            model_name='agenda',
            name='instructores_f',
        ),
        migrations.CreateModel(
            name='integracion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dias_Semana', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='agenda.dias', verbose_name='Dias')),
                ('instructores_f', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.instructor', verbose_name='Instructores')),
            ],
            options={
                'verbose_name': 'Integracion ',
                'verbose_name_plural': 'Integraciones',
            },
        ),
        migrations.AddField(
            model_name='agenda',
            name='asignacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='agenda.integracion', verbose_name='Asignar Dia'),
        ),
    ]
