# Generated by Django 4.1.3 on 2022-11-27 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0003_dias_remove_agenda_dias_remove_agenda_instructores_f_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='integracion',
            name='dias_Semana',
        ),
        migrations.AddField(
            model_name='integracion',
            name='dias_semana',
            field=models.CharField(blank=True, choices=[('L', 'Lunes'), ('M', 'Martes'), ('I', 'Miercoles'), ('J', 'Jueves'), ('V', 'Viernes'), ('S', 'Sabado')], max_length=1, null=True),
        ),
    ]
