# Generated by Django 4.1.3 on 2022-11-27 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0004_remove_integracion_dias_semana_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='integracion',
            old_name='dias_semana',
            new_name='dias_s',
        ),
    ]
