# Generated by Django 4.1.3 on 2022-11-27 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0005_rename_dias_semana_integracion_dias_s'),
    ]

    operations = [
        migrations.AlterField(
            model_name='integracion',
            name='dias_s',
            field=models.CharField(blank=True, choices=[('Lu', 'Lunes'), ('Ma', 'Martes'), ('Mi', 'Miercoles'), ('Ju', 'Jueves'), ('Vi', 'Viernes'), ('Sa', 'Sabado')], max_length=2, null=True),
        ),
    ]
