# Generated by Django 4.1.3 on 2022-11-27 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0006_alter_integracion_dias_s'),
    ]

    operations = [
        migrations.AlterField(
            model_name='integracion',
            name='dias_s',
            field=models.CharField(blank=True, choices=[('L', 'Lunes'), ('M', 'Martes'), ('I', 'Miercoles'), ('J', 'Jueves'), ('V', 'Viernes'), ('S', 'Sabado')], max_length=1, null=True),
        ),
    ]
