# Generated by Django 4.1.3 on 2022-11-27 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0007_alter_integracion_dias_s'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agenda',
            name='asignacion',
        ),
        migrations.AddField(
            model_name='agenda',
            name='dia_jueves',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Di_Jueves', to='agenda.integracion', verbose_name='Asignar Dia '),
        ),
        migrations.AddField(
            model_name='agenda',
            name='dia_lunes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Di_Lunes', to='agenda.integracion', verbose_name='Asignar Dia '),
        ),
        migrations.AddField(
            model_name='agenda',
            name='dia_martes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Di_Martes', to='agenda.integracion', verbose_name='Asignar Dia '),
        ),
        migrations.AddField(
            model_name='agenda',
            name='dia_miercoles',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Di_Miercoles', to='agenda.integracion', verbose_name='Asignar Dia '),
        ),
        migrations.AddField(
            model_name='agenda',
            name='dia_sabado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Di_Sabado', to='agenda.integracion', verbose_name='Asignar Dia '),
        ),
        migrations.AddField(
            model_name='agenda',
            name='dia_viernes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Di_Viernes', to='agenda.integracion', verbose_name='Asignar Dia '),
        ),
    ]
