# Generated by Django 4.1.3 on 2022-11-30 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0008_remove_agenda_asignacion_agenda_dia_jueves_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agenda',
            name='Titulo',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Nombre del Horario'),
        ),
    ]
