# Generated by Django 4.1.3 on 2022-11-30 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0009_agenda_titulo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agenda',
            name='Titulo',
        ),
    ]
