# Generated by Django 4.1.3 on 2022-12-01 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0010_remove_agenda_titulo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='dias',
        ),
    ]
