# Generated by Django 4.1.3 on 2022-11-04 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ambiente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_ambiente', models.CharField(max_length=200, verbose_name='Nombre del ambiente ')),
            ],
            options={
                'verbose_name': 'Ambiente',
                'verbose_name_plural': 'Ambientes',
            },
        ),
        migrations.CreateModel(
            name='horario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_Inicio', models.DateField(verbose_name='Fecha de Inicio')),
                ('fecha_Fin', models.DateField(verbose_name='Fecha Fin')),
                ('hora_Inicio_Fin', models.CharField(max_length=200, verbose_name='Hora de Inicio y Fin')),
                ('dias_Semana', models.CharField(max_length=200, verbose_name='Dias semana')),
            ],
            options={
                'verbose_name': 'Horario',
                'verbose_name_plural': 'Horarios',
            },
        ),
        migrations.CreateModel(
            name='instructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre del Instructor')),
                ('apellido', models.CharField(max_length=200, verbose_name='Apellido de instructor')),
            ],
            options={
                'verbose_name': 'Instructor',
                'verbose_name_plural': 'Instructores',
            },
        ),
        migrations.CreateModel(
            name='municipio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_municipio', models.CharField(max_length=200, verbose_name='Nombre del Municipio')),
            ],
            options={
                'verbose_name': 'Municipio',
                'verbose_name_plural': 'Municipios',
            },
        ),
        migrations.AlterModelOptions(
            name='trimestre',
            options={'verbose_name': 'Trimestre', 'verbose_name_plural': 'Trimestres'},
        ),
        migrations.AlterField(
            model_name='trimestre',
            name='nom_Trimestres',
            field=models.CharField(max_length=200, verbose_name='Nombre del Trimestre'),
        ),
    ]
