# Generated by Django 4.1.3 on 2022-11-04 19:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0002_ambiente_horario_instructor_municipio_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='centro_Formacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_Centro', models.CharField(max_length=200, verbose_name='Nombre del Centro')),
                ('id_Ambiente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.ambiente', verbose_name='Id de Ambiente')),
                ('id_Municipio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.municipio', verbose_name='Id de Municipio')),
            ],
            options={
                'verbose_name': 'Centro de formacion',
                'verbose_name_plural': 'Centros de formacion',
            },
        ),
    ]
