# Generated by Django 4.1.3 on 2022-11-19 22:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='centro_Formacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_Centro', models.CharField(max_length=200, verbose_name='Nombre del Centro')),
                ('id_Ambiente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.ambiente', verbose_name='Id de Ambiente')),
                ('id_Municipio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.municipio', verbose_name='Id de Municipio')),
                ('sede', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.sede', verbose_name='Sede')),
            ],
            options={
                'verbose_name': 'Centro de formacion',
                'verbose_name_plural': 'Centros de formacion',
            },
        ),
        migrations.CreateModel(
            name='programa_Formacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ficha', models.IntegerField(verbose_name='Ficha')),
                ('nombre_Programa', models.CharField(max_length=200, verbose_name='Nombre del Programa')),
                ('id_Centro_Formacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='programa.centro_formacion', verbose_name='Id de Centro de Formacion')),
                ('id_Instructor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.instructor', verbose_name='Id del Instructor')),
                ('tipo_Pograma', models.ForeignKey(blank=True, max_length=200, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.tipoprograma', verbose_name='Tipo de Programa')),
            ],
            options={
                'verbose_name': 'Programa de Formacion',
                'verbose_name_plural': 'Programas de Formacion',
            },
        ),
    ]
