# Generated by Django 4.1.3 on 2022-11-10 03:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='centro_Formacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_Centro', models.CharField(max_length=200, verbose_name='Nombre del Centro')),
                ('id_Ambiente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.ambiente', verbose_name='Id de Ambiente')),
                ('id_Municipio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.municipio', verbose_name='Id de Municipio')),
            ],
            options={
                'verbose_name': 'Centro de formacion',
                'verbose_name_plural': 'Centros de formacion',
            },
        ),
        migrations.CreateModel(
            name='programa_Formacion',
            fields=[
                ('ficha', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_Programa', models.CharField(max_length=200, verbose_name='Nombre del Programa')),
                ('id_Centro_Formacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='programa.centro_formacion', verbose_name='Id de Centro de Formacion')),
                ('id_Horario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.horario', verbose_name='Id de Horario')),
            ],
            options={
                'verbose_name': 'Programa de Formacion',
                'verbose_name_plural': 'Programas de Formacion',
            },
        ),
        migrations.CreateModel(
            name='trimestre_uno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_Trimestres_Uno', models.CharField(max_length=200, verbose_name='Nombre del Trimestre')),
                ('id_Programa_Formacion_Uno', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='programa.programa_formacion', verbose_name='Id Programa Formacion Uno')),
            ],
            options={
                'verbose_name': 'Trimestre Uno',
                'verbose_name_plural': 'Trimestres Uno',
            },
        ),
        migrations.CreateModel(
            name='trimestre_tres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_Trimestres_Tres', models.CharField(max_length=200, verbose_name='Nombre del Trimestre')),
                ('id_Programa_Formacion_Tres', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='programa.programa_formacion', verbose_name='Id Programa Formacion Tres')),
            ],
            options={
                'verbose_name': 'Trimestre Tres',
                'verbose_name_plural': 'Trimestres Tres',
            },
        ),
        migrations.CreateModel(
            name='trimestre_dos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_Trimestres_Dos', models.CharField(max_length=200, verbose_name='Nombre del Trimestre')),
                ('id_Programa_Formacion_Dos', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='programa.programa_formacion', verbose_name='Id Programa Formacion Dos')),
            ],
            options={
                'verbose_name': 'Trimestre Dos',
                'verbose_name_plural': 'Trimestres Dos',
            },
        ),
        migrations.CreateModel(
            name='trimestre_cuatro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_Trimestres_Cuatro', models.CharField(max_length=200, verbose_name='Nombre del Trimestre')),
                ('id_Programa_Formacion_Cuatro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='programa.programa_formacion', verbose_name='Id Programa Formacion Cuatro')),
            ],
            options={
                'verbose_name': 'Trimestre Cuatro',
                'verbose_name_plural': 'Trimestres Cuatro',
            },
        ),
        migrations.CreateModel(
            name='tipo_Instructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_Instructores', models.CharField(max_length=200, verbose_name='Tipo de Instructor')),
                ('id_Instructor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.instructor', verbose_name='Id de Instructor')),
            ],
            options={
                'verbose_name': 'Tipo Instructor',
                'verbose_name_plural': 'Tipo Instructores',
            },
        ),
        migrations.AddField(
            model_name='programa_formacion',
            name='id_Tipo_Instructor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='programa.tipo_instructor', verbose_name='Id del Tipo de Instructor'),
        ),
    ]
