# Generated by Django 4.1.3 on 2022-11-23 02:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0002_remove_agenda_cantidad_dias_remove_agenda_programa_f_and_more'),
        ('programa', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='programa_formacion',
            name='agenda',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='agenda.agenda', verbose_name='Programa'),
        ),
        migrations.AddField(
            model_name='programa_formacion',
            name='jornada',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Jornada'),
        ),
    ]
