# Generated by Django 4.1.3 on 2022-11-04 19:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_ambiente_horario_instructor_municipio_and_more'),
        ('programa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='programa_Formacion',
            fields=[
                ('ficha', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_Programa', models.CharField(max_length=200, verbose_name='Nombre del Programa')),
                ('id_Centro_Formacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programa.centro_formacion', verbose_name='Id de Centro de Formacion')),
                ('id_Horario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.horario', verbose_name='Id de Horario')),
                ('id_Trimestre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.trimestre', verbose_name='Id de Trimestre')),
            ],
            options={
                'verbose_name': 'Programa de Formacion',
                'verbose_name_plural': 'Programas de Formacion',
            },
        ),
    ]
