# Generated by Django 4.1.3 on 2022-11-30 19:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0009_agenda_titulo'),
        ('programa', '0002_programa_formacion_agenda_programa_formacion_jornada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programa_formacion',
            name='agenda',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='agenda.agenda', verbose_name='Horario'),
        ),
    ]
