# Generated by Django 4.1.3 on 2022-11-04 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programa', '0003_alter_programa_formacion_nombre_programa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programa_formacion',
            name='nombre_Programa',
            field=models.CharField(max_length=200, verbose_name='Nombre del Programa'),
        ),
    ]
