# Generated by Django 4.1.3 on 2022-11-04 20:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_ambiente_horario_instructor_municipio_and_more'),
        ('programa', '0004_alter_programa_formacion_nombre_programa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programa_formacion',
            name='nombre_Programa',
            field=models.CharField(max_length=200, verbose_name='Nombre del Centro'),
        ),
        migrations.CreateModel(
            name='tipo_Instructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_Instructores', models.CharField(max_length=200, verbose_name='Tipo de Instructor')),
                ('id_Instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.instructor', verbose_name='Id de Instructor')),
                ('id_Programa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programa.programa_formacion', verbose_name='Id programa de Formacion')),
            ],
            options={
                'verbose_name': 'Tipo Instructor',
                'verbose_name_plural': 'Tipo Instructores',
            },
        ),
    ]
